# Generated by Django 4.1.5 on 2023-01-28 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLink',
            fields=[
                ('entry_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='api.entry')),
                ('centroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centroid', to='api.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entry_links',
            },
        ),
        migrations.RemoveField(
            model_name='collectionentry',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionentry',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='collectionentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionEntry',
        ),
    ]
