# Generated by Django 4.1.5 on 2023-02-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cluster_clusterlink'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cluster',
            table='clusters',
        ),
        migrations.AlterModelTable(
            name='clusterlink',
            table='cluster_links',
        ),
    ]
