# Generated by Django 4.1.5 on 2023-02-03 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cluster_table_alter_clusterlink_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringAlgorithm',
            fields=[
                ('clustering_algorithm_id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.BinaryField(default=b'0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clustering_algorithm',
            },
        ),
    ]
