# Generated by Django 4.1.5 on 2023-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
